// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnfttxvxsohjgntpezhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZnR0eHZ4c29oamdudHBlemh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTM2MTYsImV4cCI6MjA1ODQyOTYxNn0.ypL4Q_8NyQT12-Gr79KOHuOuH5vgz2J3lzpERY5FEn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);